### ISSUE TITLE
Make `main` a special function.

### ISSUE THREAD

**Issue by m-lopez** [m-lopez/jack#19]
Allow the definition of a `main` constant. It must have `Int` type.
```
main: Int := ...
````
In the future, we should have a special type for status codes and accept other signatures for `main`.

**Comment by jhorowitz** [comment]
Why does main return an int? Wouldn't getting to the bottom of the main function without a panic imply 0?

**Comment by m-lopez** [comment]
In many systems, when a process terminates, it returns a status code value to its parent process. For example, bash uses these for it's `cmd1 && cmd2` operator which will only execute `cmd2` if the status code returned by `cmd1` is the success code.

For more, see https://en.wikipedia.org/wiki/Exit_status.

I want toaster programs to take advantage of this. So it can return an Int in the short term. Ideally this status codes should be their own type that is different per system.

**Comment by m-lopez** [comment]
This was covered in #23.
